import { test as base, expect } from '@playwright/test';
import { LoginPage } from '@pages/auth/login.page';
import { CandidatesListPage } from '@pages/candidates/candidates-list.page';
import { CandidateDetailPage } from '@pages/candidates/candidate-detail.page';
import { JobsListPage } from '@pages/jobs/jobs-list.page';
import { AuthApi } from '@api/auth-api';
import { CandidatesApi } from '@api/candidates-api';
import { AUTH_STATE_PATHS } from '@constants/index';
import { getAdminCredentials } from '@factories/user-data';

type Fixtures = {
  loginPage: LoginPage;
  candidatesListPage: CandidatesListPage;
  candidateDetailPage: CandidateDetailPage;
  jobsListPage: JobsListPage;
  authApi: AuthApi;
  candidatesApi: CandidatesApi;
};

export const test = base.extend<Fixtures>({
  loginPage: async ({ page }, use) => {
    await use(new LoginPage(page));
  },

  candidatesListPage: async ({ page }, use) => {
    await use(new CandidatesListPage(page));
  },

  candidateDetailPage: async ({ page }, use) => {
    await use(new CandidateDetailPage(page));
  },

  jobsListPage: async ({ page }, use) => {
    await use(new JobsListPage(page));
  },

  authApi: async ({ request }, use) => {
    await use(new AuthApi(request));
  },

  // Creates a fresh token per test. Fine for the current test count.
  // If login latency becomes a problem, this can move to worker scope.
  candidatesApi: async ({ request }, use) => {
    const creds = getAdminCredentials();
    const authApi = new AuthApi(request);
    const tokenData = await authApi.login(creds.email, creds.password);
    await use(new CandidatesApi(request, tokenData.accessToken));
  },
});

// Tests that need an authenticated browser session use this.
// The storageState file is generated by auth.setup.ts before the suite runs.
export const authenticatedTest = test.extend({
  storageState: AUTH_STATE_PATHS.ADMIN,
});

export { expect };
